// Persian (فارسی) strings. Keys are the English text used in the code.
// Anything missing here falls back to English, so a gap never breaks a page.
export const fa: Record<string, string> = {
  // Navigation and top bar
  "Dashboard": "داشبورد",
  "Devices": "دستگاه‌ها",
  "Ports": "پورت‌ها",
  "Alerts": "هشدارها",
  "Availability": "دسترس‌پذیری",
  "Services": "سرویس‌ها",
  "Logs": "گزارش‌ها",
  "Network map": "نقشه شبکه",
  "Performance": "عملکرد",
  "Settings": "تنظیمات",
  "Main navigation": "ناوبری اصلی",
  "Refresh": "تازه‌سازی",
  "Refresh now": "تازه‌سازی اکنون",
  "Off": "خاموش",
  "{s} s": "{s} ثانیه",
  "{m} min": "{m} دقیقه",
  "Switch to light theme": "تغییر به پوسته روشن",
  "Switch to dark theme": "تغییر به پوسته تاریک",
  "Switch language": "تغییر زبان",
  "Checking connection": "در حال بررسی اتصال",
  "Backend offline": "سرور واسط در دسترس نیست",
  "Sample data": "داده نمونه",
  "LibreNMS {version}": "LibreNMS نسخه {version}",
  "LibreNMS connected": "اتصال به LibreNMS برقرار است",
  "LibreNMS unreachable": "LibreNMS در دسترس نیست",
  "The backend is not reachable. Start it on port 8000.": "سرور واسط در دسترس نیست. آن را روی پورت 8000 اجرا کنید.",
  "The backend is not reachable. Check the backend address in Settings.": "سرور واسط در دسترس نیست. آدرس سرور واسط را در تنظیمات بررسی کنید.",
  "Page not found": "صفحه پیدا نشد",
  "This page is built in a later step.": "این صفحه در مرحله‌ای بعدی ساخته می‌شود.",

  // Common
  "Up": "فعال",
  "Down": "قطع",
  "Not up": "غیرفعال",
  "Ok": "سالم",
  "Warning": "هشدار",
  "Critical": "بحرانی",
  "Error": "خطا",
  "Info": "اطلاعات",
  "Notice": "اعلان",
  "Unknown": "نامشخص",
  "Device": "دستگاه",
  "Device {id}": "دستگاه {id}",
  "device {id}": "دستگاه {id}",
  "Status": "وضعیت",
  "State": "حالت",
  "Time": "زمان",
  "Level": "سطح",
  "Message": "پیام",
  "Location": "مکان",
  "Uptime": "مدت روشن بودن",
  "OS": "سیستم‌عامل",
  "CPU": "پردازنده",
  "Memory": "حافظه",
  "Speed": "سرعت",
  "In": "ورودی",
  "Out": "خروجی",
  "Port": "پورت",
  "Port {id}": "پورت {id}",
  "Loading": "در حال بارگذاری",
  "Previous": "قبلی",
  "Next": "بعدی",
  "{from} to {to} of {total}": "{from} تا {to} از {total}",
  "All statuses": "همه وضعیت‌ها",
  "Filter by status": "فیلتر بر اساس وضعیت",
  "Actions": "عملیات",
  "Cancel": "انصراف",
  "All": "همه",

  // Time units
  "{d} d {h} h": "{d} روز و {h} ساعت",
  "{h} h {m} min": "{h} ساعت و {m} دقیقه",
  "{n} days": "{n} روز",
  "24 hours": "۲۴ ساعت",
  "7 days": "۷ روز",
  "30 days": "۳۰ روز",
  "1 year": "۱ سال",
  "Last {period}": "{period} گذشته",

  // Dashboard
  "Devices up": "دستگاه‌های فعال",
  "Devices down": "دستگاه‌های قطع",
  "{up} of {total}": "{up} از {total}",
  "Active alerts": "هشدارهای فعال",
  "{n} critical": "{n} بحرانی",
  "Services not ok": "سرویس‌های ناسالم",
  "of {n}": "از {n}",
  "Needs attention": "نیازمند توجه",
  "Showing 10 of {n}": "نمایش ۱۰ مورد از {n}",
  "Nothing needs attention. All devices are up and no alerts are active.": "موردی نیاز به توجه ندارد. همه دستگاه‌ها فعال‌اند و هشدار فعالی وجود ندارد.",
  "Recent events": "رویدادهای اخیر",
  "All logs": "همه گزارش‌ها",
  "No recent events.": "رویداد اخیری وجود ندارد.",
  "Device down": "دستگاه قطع است",
  "Critical alert": "هشدار بحرانی",
  "Alert": "هشدار",
  "Service": "سرویس",
  "Service critical": "سرویس بحرانی",
  "Service warning": "هشدار سرویس",
  "{time} on {device}": "{time} در {device}",
  "Rule {id}": "قانون {id}",

  // Devices
  "Loading devices": "در حال بارگذاری دستگاه‌ها",
  "{n} devices, {down} down": "{n} دستگاه، {down} قطع",
  "Search name, IP, OS, location": "جستجوی نام، آی‌پی، مکان",
  "Search devices": "جستجوی دستگاه‌ها",
  "No devices yet. Add devices in LibreNMS and they appear here.": "هنوز دستگاهی وجود ندارد. دستگاه‌ها را در LibreNMS اضافه کنید تا اینجا نمایش داده شوند.",
  "No devices match these filters.": "هیچ دستگاهی با این فیلترها مطابقت ندارد.",

  // Device details
  "Overview": "نمای کلی",
  "Hostname": "نام میزبان",
  "IP address": "آدرس آی‌پی",
  "Operating system": "سیستم‌عامل",
  "Hardware": "سخت‌افزار",
  "Last polled": "آخرین پایش",
  "Resources": "منابع",
  "Loading resources": "در حال بارگذاری منابع",
  "No CPU, memory or storage data reported for this device.": "داده‌ای از پردازنده، حافظه یا فضای ذخیره‌سازی این دستگاه گزارش نشده است.",
  "Loading availability": "در حال بارگذاری دسترس‌پذیری",
  "No availability data for this device.": "داده دسترس‌پذیری برای این دستگاه وجود ندارد.",
  "Downtime events": "رویدادهای قطعی",
  "Loading downtime events": "در حال بارگذاری رویدادهای قطعی",
  "No downtime recorded.": "قطعی‌ای ثبت نشده است.",
  "Went down": "زمان قطع شدن",
  "Came back": "زمان بازگشت",
  "Duration": "مدت",
  "Still down": "هنوز قطع است",
  "Only ports that are up": "فقط پورت‌های فعال",
  "Loading ports": "در حال بارگذاری پورت‌ها",
  "No ports to show.": "پورتی برای نمایش وجود ندارد.",

  // Ports
  "{n} ports, {down} not up": "{n} پورت، {down} غیرفعال",
  "Search port, label, device": "جستجوی پورت، برچسب، دستگاه",
  "Search ports": "جستجوی پورت‌ها",
  "Filter by device": "فیلتر بر اساس دستگاه",
  "All devices": "همه دستگاه‌ها",
  "Disabled": "غیرفعال شده",
  "No ports reported yet.": "هنوز پورتی گزارش نشده است.",
  "No ports match these filters.": "هیچ پورتی با این فیلترها مطابقت ندارد.",

  // Alerts
  "Loading alerts": "در حال بارگذاری هشدارها",
  "{n} active": "{n} فعال",
  "{n} acknowledged": "{n} تأییدشده",
  "{n} alerts": "{n} هشدار",
  "Alert state": "وضعیت هشدار",
  "Active": "فعال",
  "Acknowledged": "تأییدشده",
  "Cleared": "رفع‌شده",
  "All severities": "همه شدت‌ها",
  "Filter by severity": "فیلتر بر اساس شدت",
  "Severity": "شدت",
  "Raised": "زمان وقوع",
  "Acknowledge": "تأیید دریافت",
  "Acknowledge alert": "تأیید دریافت هشدار",
  "Acknowledging": "در حال ثبت تأیید",
  "{rule} on {device}": "{rule} روی {device}",
  "Note (optional)": "یادداشت (اختیاری)",
  "Keep acknowledged until the alert clears": "تا زمان رفع هشدار در حالت تأییدشده بماند",
  "No active alerts. Everything is running within its rules.": "هشدار فعالی وجود ندارد. همه‌چیز در چارچوب قوانین کار می‌کند.",
  "No alerts match these filters.": "هیچ هشداری با این فیلترها مطابقت ندارد.",

  // Availability
  "Share of time each device answered polling. Values under 99% are highlighted.": "درصد زمانی که هر دستگاه به پایش پاسخ داده است. مقادیر زیر ۹۹٪ پررنگ نمایش داده می‌شوند.",
  "Search name, IP, location": "جستجوی نام، آی‌پی، مکان",
  "No devices yet.": "هنوز دستگاهی وجود ندارد.",
  "No devices match this search.": "هیچ دستگاهی با این جستجو مطابقت ندارد.",

  // Services
  "Loading services": "در حال بارگذاری سرویس‌ها",
  "{n} services, {bad} not ok": "{n} سرویس، {bad} ناسالم",
  "Search service, device, message": "جستجوی سرویس، دستگاه، پیام",
  "Search services": "جستجوی سرویس‌ها",
  "Not ok": "ناسالم",
  "Changed": "زمان تغییر",
  "No services are configured in LibreNMS.": "هیچ سرویسی در LibreNMS تنظیم نشده است.",
  "No services match these filters.": "هیچ سرویسی با این فیلترها مطابقت ندارد.",

  // Logs
  "Latest {n} entries": "آخرین {n} مورد",
  "Log type": "نوع گزارش",
  "Events": "رویدادها",
  "Syslog": "سیس‌لاگ",
  "Alert history": "تاریخچه هشدارها",
  "Search message or device": "جستجوی پیام یا دستگاه",
  "Search logs": "جستجوی گزارش‌ها",
  "Loading logs": "در حال بارگذاری گزارش‌ها",
  "No log entries returned.": "گزارشی دریافت نشد.",
  "No entries match this search.": "هیچ موردی با این جستجو مطابقت ندارد.",

  // Network map
  "Built from LLDP and CDP neighbour links that LibreNMS has discovered. Select a device to see its links.": "بر اساس لینک‌های همسایه (LLDP و CDP) که LibreNMS کشف کرده ساخته شده است. برای دیدن لینک‌ها، یک دستگاه را انتخاب کنید.",
  "Topology": "توپولوژی",
  "No neighbour links found. Enable LLDP or CDP on your switches and run discovery in LibreNMS.": "لینک همسایه‌ای پیدا نشد. LLDP یا CDP را روی سوئیچ‌ها فعال کنید و در LibreNMS کشف را اجرا کنید.",
  "Zoom in": "بزرگ‌نمایی",
  "Zoom out": "کوچک‌نمایی",
  "Reset view": "بازنشانی نما",
  "Network topology map": "نقشه توپولوژی شبکه",
  "not monitored": "پایش نمی‌شود",
  "Seen by neighbour discovery, not in LibreNMS": "توسط کشف همسایه دیده شده، در LibreNMS نیست",
  "{n} devices, {l} links": "{n} دستگاه، {l} لینک",
  "Links": "لینک‌ها",
  "Select a device on the map to list its links.": "برای دیدن فهرست لینک‌ها، یک دستگاه را روی نقشه انتخاب کنید.",
  "Open device page": "باز کردن صفحه دستگاه",
  "This device was seen through LLDP or CDP but is not monitored in LibreNMS.": "این دستگاه از طریق LLDP یا CDP دیده شده اما در LibreNMS پایش نمی‌شود.",

  // Performance
  "Live traffic for one port. The chart starts when you pick a port and only covers the time this page stays open.": "ترافیک زنده یک پورت. نمودار از لحظه انتخاب پورت شروع می‌شود و فقط بازه‌ای را نشان می‌دهد که این صفحه باز بوده است.",
  "Choose a device": "یک دستگاه انتخاب کنید",
  "Choose a port": "یک پورت انتخاب کنید",
  "Sample every": "نمونه‌برداری هر",
  "Traffic": "ترافیک",
  "{n} samples": "{n} نمونه",
  "Choose a device and a port to start charting.": "برای شروع نمودار، یک دستگاه و یک پورت انتخاب کنید.",
  "Waiting for the second sample. The next one arrives within {wait}.": "در انتظار نمونه دوم. نمونه بعدی حداکثر تا {wait} دیگر می‌رسد.",
  "LibreNMS recalculates these rates only when it polls the device, every 5 minutes by default. Sampling faster than that repeats the same value.": "LibreNMS این نرخ‌ها را فقط هنگام پایش دستگاه (به‌طور پیش‌فرض هر ۵ دقیقه) دوباره محاسبه می‌کند. نمونه‌برداری سریع‌تر از آن، همان مقدار را تکرار می‌کند.",
  "History": "تاریخچه",
  "Charts for the last hour to the last 30 days need a metric store (Prometheus or InfluxDB). They are not wired up yet.": "نمودارهای یک ساعت تا ۳۰ روز گذشته به یک ذخیره‌گاه متریک (Prometheus یا InfluxDB) نیاز دارند. هنوز متصل نشده‌اند.",

  // Settings
  "LibreNMS connection": "اتصال به LibreNMS",
  "Server URL": "آدرس سرور",
  "API token": "توکن API",
  "A token is saved. Enter a new one to replace it.": "یک توکن ذخیره شده است. برای جایگزینی، توکن جدید وارد کنید.",
  "Paste a token": "توکن را جای‌گذاری کنید",
  "The token is sent to the backend and never shown again.": "توکن به سرور واسط ارسال می‌شود و دیگر نمایش داده نمی‌شود.",
  "Settings saved.": "تنظیمات ذخیره شد.",
  "Save settings": "ذخیره تنظیمات",
  "Saving": "در حال ذخیره",
  "Test connection": "آزمایش اتصال",
  "Testing": "در حال آزمایش",
  "Not configured, showing sample data.": "پیکربندی نشده است و داده نمونه نمایش داده می‌شود.",
  "Connected to LibreNMS {version}.": "اتصال به LibreNMS نسخه {version} برقرار شد.",
  "Connected.": "اتصال برقرار شد.",
  "LibreNMS did not answer.": "LibreNMS پاسخ نداد.",
  "Without a server URL and token the app shows sample data.": "بدون آدرس سرور و توکن، برنامه داده نمونه نمایش می‌دهد.",
  "This browser": "این مرورگر",
  "Theme": "پوسته",
  "Dark. Switch to light": "تاریک. تغییر به روشن",
  "Light. Switch to dark": "روشن. تغییر به تاریک",
  "Language": "زبان",
  "Auto-refresh": "تازه‌سازی خودکار",

  // Add device
  "Add device": "افزودن دستگاه",
  "Add another device": "افزودن دستگاه دیگر",
  "Device added.": "دستگاه اضافه شد.",
  "Add a server, switch, router or client to monitoring without opening LibreNMS.": "یک سرور، سوئیچ، روتر یا کلاینت را بدون باز کردن LibreNMS به پایش اضافه کنید.",
  "Monitoring type": "نوع پایش",
  "SNMP device": "دستگاه SNMP",
  "For servers, switches and routers that answer SNMP.": "برای سرورها، سوئیچ‌ها و روترهایی که به SNMP پاسخ می‌دهند.",
  "Ping only": "فقط پینگ",
  "For clients and anything without SNMP. Only reachability is monitored.": "برای کلاینت‌ها و هر دستگاهی که SNMP ندارد. فقط دسترسی‌پذیری پایش می‌شود.",
  "Hostname or IP address": "نام میزبان یا آدرس آی‌پی",
  "Display name (optional)": "نام نمایشی (اختیاری)",
  "Location (optional)": "مکان (اختیاری)",
  "Hardware (optional)": "سخت‌افزار (اختیاری)",
  "Operating system (optional)": "سیستم‌عامل (اختیاری)",
  "Sets the icon in LibreNMS, for example linux or windows.": "آیکن را در LibreNMS تعیین می‌کند، مثلاً linux یا windows.",
  "SNMP version": "نسخه SNMP",
  "Community": "کامیونیتی",
  "Security level": "سطح امنیت",
  "Username": "نام کاربری",
  "Authentication password": "رمز احراز هویت",
  "Authentication algorithm": "الگوریتم احراز هویت",
  "Privacy password": "رمز حریم خصوصی",
  "Privacy algorithm": "الگوریتم حریم خصوصی",
  "Credentials are sent to the backend and never shown again.": "اطلاعات ورود به سرور واسط ارسال می‌شود و دیگر نمایش داده نمی‌شود.",
  "Advanced options": "گزینه‌های پیشرفته",
  "SNMP port": "پورت SNMP",
  "Leave empty for the default (161).": "برای مقدار پیش‌فرض (۱۶۱) خالی بگذارید.",
  "Transport": "پروتکل انتقال",
  "Default": "پیش‌فرض",
  "If SNMP fails, add as ping only": "اگر SNMP شکست خورد، به‌صورت فقط پینگ اضافه شود",
  "Add even if the device does not answer now": "حتی اگر دستگاه اکنون پاسخ نمی‌دهد، اضافه شود",
  "Skips the reachability and SNMP checks. The device is added exactly as entered and shows as down until it responds.": "بررسی دسترسی و SNMP را رد می‌کند. دستگاه دقیقاً با مقادیر واردشده اضافه می‌شود و تا زمان پاسخ‌دهی قطع نمایش داده می‌شود.",
  "Adding": "در حال افزودن",
  "New devices fill in with full data after LibreNMS finishes discovery, usually within a few minutes.": "اطلاعات کامل دستگاه‌های جدید پس از پایان کشف در LibreNMS، معمولاً طی چند دقیقه، نمایش داده می‌شود.",
  "Enter a hostname or IP address.": "نام میزبان یا آدرس آی‌پی را وارد کنید.",
  "The hostname can only contain letters, digits, dots, dashes, underscores and colons.": "نام میزبان فقط می‌تواند شامل حروف، ارقام، نقطه، خط تیره، زیرخط و دونقطه باشد.",
  "The port must be a number from 1 to 65535.": "پورت باید عددی بین ۱ تا ۶۵۵۳۵ باشد.",
  "Enter the SNMP community.": "کامیونیتی SNMP را وارد کنید.",
  "Enter the SNMPv3 username.": "نام کاربری SNMPv3 را وارد کنید.",
  "Enter the authentication password.": "رمز احراز هویت را وارد کنید.",
  "Enter the privacy password.": "رمز حریم خصوصی را وارد کنید.",

  // Remove device
  "Remove device": "حذف دستگاه",
  "Removing": "در حال حذف",
  "This removes {name} from LibreNMS together with its history, graphs and alerts. It cannot be undone.": "{name} همراه با تاریخچه، نمودارها و هشدارهایش از LibreNMS حذف می‌شود. این کار قابل بازگشت نیست.",
  "Type {host} to confirm.": "برای تأیید، {host} را تایپ کنید.",

  // Backend address
  "Backend address": "آدرس سرور واسط",
  "Padi backend URL": "نشانی سرور واسط پدی",
  "Leave empty to use the same address this page was loaded from.": "برای استفاده از همان آدرسی که این صفحه از آن بارگذاری شده، خالی بگذارید.",
  "Save address": "ذخیره آدرس",
  "Test backend": "آزمایش سرور واسط",
  "Backend reachable.": "سرور واسط در دسترس است.",
  "Backend address saved.": "آدرس سرور واسط ذخیره شد.",
  "Cannot reach the backend at this address (check the address, that it is running, and CORS).": "اتصال به سرور واسط در این آدرس برقرار نشد (آدرس، در حال اجرا بودن سرور و تنظیم CORS را بررسی کنید).",

  // Device details
  "Type": "نوع",
  "Serial number": "شماره سریال",
  "Firmware version": "نسخه سیستم‌افزار",
  "Monitoring": "روش پایش",
  "Last ping": "آخرین پینگ",
  "Status reason": "دلیل وضعیت",
  "Description": "توضیحات",

  // Scan network
  "Scan network": "اسکن شبکه",
  "Scan": "اسکن",
  "Scanning": "در حال اسکن",
  "Find every device that answers on an IP range and add them all at once.": "همه دستگاه‌هایی را که در یک بازه آی‌پی پاسخ می‌دهند پیدا کنید و یکجا اضافه کنید.",
  "IP range": "بازه آی‌پی",
  "Range to scan": "بازه مورد اسکن",
  "Examples: 172.16.32.0/24, 172.16.32. or 172.16.32.10-50. Up to 1024 addresses.": "نمونه: 172.16.32.0/24 یا 172.16.32. یا 172.16.32.10-50. حداکثر ۱۰۲۴ آدرس.",
  "Devices found": "دستگاه‌های پیداشده",
  "Nothing answered ping in this range. Devices that block ping will not appear; add those one by one.": "هیچ دستگاهی در این بازه به پینگ پاسخ نداد. دستگاه‌هایی که پینگ را مسدود کرده‌اند نمایش داده نمی‌شوند؛ آن‌ها را یکی‌یکی اضافه کنید.",
  "{n} of {total} addresses answered": "{n} آدرس از {total} آدرس پاسخ دادند",
  "already monitored": "از قبل پایش می‌شوند",
  "Already monitored": "از قبل پایش می‌شود",
  "New": "جدید",
  "Name": "نام",
  "Select all": "انتخاب همه",
  "How to add them": "روش افزودن",
  "Ping only (clients without SNMP)": "فقط پینگ (کلاینت‌های بدون SNMP)",
  "SNMP community": "کامیونیتی SNMP",
  "Add even if LibreNMS cannot reach them now": "حتی اگر LibreNMS اکنون به آن‌ها دسترسی ندارد، اضافه شوند",
  "Add selected": "افزودن موارد انتخاب‌شده",
  "This can take a while: LibreNMS checks each device.": "ممکن است کمی طول بکشد: LibreNMS هر دستگاه را بررسی می‌کند.",
  "Result": "نتیجه",
  "added": "اضافه شد",
  "failed": "ناموفق",
  "Enter an IP range to scan, for example 172.16.32.0/24.": "بازه آی‌پی مورد اسکن را وارد کنید، مثلاً 172.16.32.0/24.",
  "Select at least one device to add.": "دست‌کم یک دستگاه را برای افزودن انتخاب کنید.",
  "Enter the SNMP community, or choose ping only.": "کامیونیتی SNMP را وارد کنید یا «فقط پینگ» را انتخاب کنید.",

  // Backend messages
  "A host name or IP address is required.": "نام میزبان یا آدرس آی‌پی لازم است.",
  "That is not a valid IPv4 range. Use 172.16.32.0/24, 172.16.32. or 172.16.32.10-50.": "این یک بازه IPv4 معتبر نیست. از 172.16.32.0/24 یا 172.16.32. یا 172.16.32.10-50 استفاده کنید.",
  "That range is too large. The limit is 1024 addresses (a /22).": "این بازه بیش از حد بزرگ است. حداکثر ۱۰۲۴ آدرس (یک /22) مجاز است.",
  "Add at most 256 devices at a time.": "در هر بار حداکثر ۲۵۶ دستگاه اضافه کنید.",
  "One of the selected addresses is not a valid IPv4 address.": "یکی از آدرس‌های انتخاب‌شده یک آدرس IPv4 معتبر نیست.",
  "LibreNMS URL or API token is not configured.": "آدرس LibreNMS یا توکن API تنظیم نشده است.",
  "LibreNMS server did not respond in time.": "سرور LibreNMS در زمان مقرر پاسخ نداد.",
  "LibreNMS server is unreachable.": "سرور LibreNMS در دسترس نیست.",
  "API authentication failed.": "احراز هویت API ناموفق بود.",
  "The API token is not allowed to access this resource.": "توکن API اجازه دسترسی به این مورد را ندارد.",
  "The requested item was not found in LibreNMS.": "مورد درخواستی در LibreNMS پیدا نشد.",
  "LibreNMS reported an internal error.": "LibreNMS یک خطای داخلی گزارش کرد.",
  "LibreNMS rejected the request.": "LibreNMS درخواست را نپذیرفت.",
  "LibreNMS returned an invalid response.": "LibreNMS پاسخ نامعتبر برگرداند.",
  "LibreNMS returned an empty response.": "LibreNMS پاسخ خالی برگرداند.",
  "Device not found.": "دستگاه پیدا نشد.",
  "Port not found.": "پورت پیدا نشد.",

  // Mobile
  "Open menu": "باز کردن منو",
  "Close menu": "بستن منو",
  "Sort by": "مرتب‌سازی بر اساس",

  // Open ports
  "No open ports found. Ports behind a firewall also look closed.": "پورت بازی پیدا نشد. پورت‌هایی که فایروال پشت آن‌هاست هم بسته به نظر می‌رسند.",
  "Enter a valid IPv4 address.": "یک آدرس IPv4 معتبر وارد کنید.",
  "Only private network addresses can be checked.": "فقط آدرس‌های شبکه خصوصی قابل بررسی هستند.",
  "Port scan": "اسکن پورت",
  "Ports to scan": "پورت‌های مورد اسکن",
  "Scan only known ports": "فقط پورت‌های شناخته‌شده",
  "Scan ports range": "اسکن بازه‌ای از پورت‌ها",
  "From port": "از پورت",
  "To port": "تا پورت",
  "Start scan": "شروع اسکن",
  "Stop scan": "توقف اسکن",
  "Scan stopped": "اسکن متوقف شد",
  "Scan failed": "اسکن ناموفق بود",
  "Scan finished": "اسکن تمام شد",
  "Scan progress": "پیشرفت اسکن",
  "listening": "در حال گوش دادن",
  "Nothing found yet.": "هنوز چیزی پیدا نشده است.",
  "Enter a port range between 1 and 65535.": "بازه پورت را بین ۱ تا ۶۵۵۳۵ وارد کنید.",
  "Too many scans are running. Wait for one to finish.": "اسکن‌های زیادی در حال اجراست. صبر کنید یکی تمام شود.",
  "This scan no longer exists. Start a new one.": "این اسکن دیگر وجود ندارد. اسکن جدیدی شروع کنید.",
};
